server:
  port: 8081
spring:
  application:
    name: smart_life-plus
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true  
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere.yaml
  data:
    redis:
      database: 0
      host: ip
      port: 6379
      password: yourpassword
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1    
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字?    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  kafka:
    bootstrap-servers: ip:9092
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      #默认的消费组ID
      group-id: create_voucher_order
      #是否自动提交offset - 改为自动提交
      enable-auto-commit: true
      #提交offset延时
      auto-commit-interval: 200
      # 当kafka中没有初始offset或offset超出范围时将自动重置offset
      # earliest:重置为分区中最小的offset;
      # latest:重置为分区中最新的offset(消费分区中新产生的数?;
      # none:只要有一个分区不存在已提交的offset,就抛出异?
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
mybatis-plus:
  type-aliases-package: org.javaup.entity # 别名扫描?
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
logging:
  level:
    org.javaup: info
    AUDIT: INFO
  pattern:
    dateformat: mm:ss.SSS
bloom-filter:
  filters:
    shop:
      name: shop-id-bloom
      expected-insertions: 50000
      false-probability: 0.01
    voucher:
      name: voucher-id-bloom
      expected-insertions: 100000
      false-probability: 0.01
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
agent:
  python:
    enabled: true
    chat-url: http://localhost:8000/chat
